name: venturo_core
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  amplitude_flutter: ^4.3.2
  app_links: ^6.4.0
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  fast_rsa: ^3.6.6
  firebase_analytics: ^11.3.2
  firebase_core: ^3.6.0
  firebase_messaging: ^15.1.2
  flutter:
    sdk: flutter
  flutter_flavorizr: ^2.2.3
  flutter_local_notifications: ^17.2.3
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.17
  get: ^4.6.6
  google_fonts: ^6.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  package_info_plus: ^8.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pull_to_refresh: ^2.0.0
  qr_flutter: ^4.1.0
  sentry_flutter: ^8.13.2
  shimmer: ^3.0.0
  venturo_api_manager: ^1.0.1
  vpack: ^1.0.0

dev_dependencies:
  build_runner: ^2.4.6

  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
